version: 2

jobs:
  build:
    working_directory: ~/aws-lambda-graphql
    docker:
      - image: circleci/node:10.17.0
    steps:
      - checkout
      - run:
          name: Installing javascript dependencies
          command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build packages (typecheck)
          command: |
            yarn build
      - run:
          name: Testing the source code
          command: yarn test:ci

workflows:
  version: 2
  test:
    jobs:
      - build
